title: "~gansanay" # Used for SEO/browser tabs, but not displayed on page
description: Guillaume Ansanay-Alex's notes
url: "https://gansanay.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
linkedin_url: "https://www.linkedin.com/in/gansanay/"

# Build settings
markdown: kramdown
permalink: /:title/